image: privacybydesign/irma:latest

stages:
  - verify

before_script:
  - set -euxo pipefail
  - ln -s "$CI_PROJECT_DIR" "/tmp/pbdf"
  - cd /tmp/pbdf

verify:
  stage: verify
  artifacts:
    paths:
      - ./*
  script:
    - irma scheme verify
